FROM node:12.20.1-alpine3.12

WORKDIR /usr/src/app

COPY package*.json ./

###  Installing dependencies

RUN npm install --silent

# copy local files to app folder
COPY . .

RUN npm run build

EXPOSE 3001

CMD [ "node", "app.js" ]